"""add Department

Revision ID: 405433c17b3c
Revises: bf81f8a46879
Create Date: 2024-10-03 13:43:11.339025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '405433c17b3c'
down_revision = 'bf81f8a46879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
